### PR TITLE
Fix compilation for Nim devel 0.19.9 (or Nim 0.20+)

### PR DESCRIPTION
**Pull request by kaushalmodi**
**Wait for Nim 0.20.0 to be released before merging this.**

---

- Fixes the int/cint type mismatch
- Complex type is now generic and not a tuple anymore.

### CODE REVIEW

**Comment by m13253** [comment]
Thank you for your contribution!

**Comment by kaushalmodi** [comment]
@m13253 Oh no, you merged it too soon!

**Comment by kaushalmodi** [comment]
Thanks for merging thought, but this specific PR will work only on Nim devel or the next major Nim stable release (0.20.0).

**Comment by m13253** [comment]
Oops! I will revert this merge as soon as I have access to a computer. And merge again after the stable release.

**Comment by kaushalmodi** [comment]
@m13253 Actually I can send one more PR that will make the change in this PR work for both Nim 0.19.9 and older versions.

**Comment by timotheecour** [comment]
@kaushalmodi maybe adapt this: https://github.com/nitely/nim-regex/pull/34 and send a new PR ?

**Comment by kaushalmodi** [comment]
@timotheecour Thanks, yes, will do that .. coming up in 3rd PR.

**Pull request merged**
